apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmail
  namespace: argocd
spec:
  project: default   # ✅ Specify an ArgoCD project (change if needed)
  source:
    repoURL: https://github.com/OpenMail-lab/OpenMail.git
    targetRevision: main
    path: helm/
  destination:
    server: https://kubernetes.default.svc
    namespace: openmail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
