apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openmail-self-update
spec:
  source:
    repoURL: https://github.com/openmail-lab/OpenMail.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: openmail
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
